@echo off
echo Initializing Git repository...
git init

echo Adding files...
git add .

echo Committing files...
git commit -m "Initial commit"

echo Setting main branch...
git branch -M main

echo Adding remote repository...
git remote add origin https://github.com/Rudrapatel330/sharetoall330.git

echo Pushing to GitHub...
git push -u origin main

echo Done! Press any key to exit...
pause
